### ISSUE TITLE
Application of PROJECTED gradient ascent

### ISSUE THREAD

**Issue by 4kills** [cherise215/advchain#3]
First of all, thank you very much for your amazing contribution to the field!

I just have a short question regarding your code and how it relates to your paper. In the paper, for each transformation, there are several constraints on the feasible solution set for the optimized adverserial transformation parameters. For example, for the noise data, the l2-norm or the noise r must be smaller than epsilon. 
To that end, it is stated in the paper that you employ projected gradient ascent.

However, when I check the code for optimizing the parameters in the noise transformation, I see standard gradient ascent (t_i+1 = t_i + step * grad) without a projection step afterwards. Am I missing anything? 

Thank you very much, especially if this is a dumb question.

**Comment by cherise215** [comment]
Hi,  there is a rescale_parameter function implemented for this purpose, called after optimisation. see, https://github.com/cherise215/advchain/blob/master/advchain/augmentor/adv_compose_solver.py#L373.
